export type MessageRole = "system" | "user" | "assistant";

export interface MessageRecord {
  id: string;
  conversationId: string;
  role: MessageRole;
  content: string;
  metadata: Record<string, unknown>;
  /** Semantic embedding vector for hybrid message search.
   *  Written when an embedding provider is configured. */
  embedding?: number[];
  createdAt: string;
}

export interface CreateMessageInput {
  id?: string;
  conversationId: string;
  role: MessageRole;
  content: string;
  metadata?: Record<string, unknown>;
  /** OSS attachment references persisted in metadata.attachments */
  attachments?: Array<{
    id: string;
    name: string;
    type: string;
    sizeBytes?: number;
    url?: string;
    storageKey?: string;
  }>;
  /** Optional embedding vector for semantic message search.
   *  Generated by LlmEmbeddingService when a real provider is available. */
  embedding?: number[];
}

export interface MessageRepository {
  create(input: CreateMessageInput): Promise<MessageRecord>;
  listByConversationId(conversationId: string): Promise<MessageRecord[]>;
}
