export type ChatRole = "system" | "user" | "assistant" | "tool";

// ── Native Function Calling Types ─────────────────────────────────────
// OpenAI-compatible tool calling structures for LLM-driven tool selection.

/** A tool definition sent to the LLM as part of the request. */
export interface ToolDefinition {
  type: "function";
  function: {
    name: string;
    description: string;
    parameters: Record<string, unknown>; // JSON Schema
  };
}

/** A complete tool call returned by the LLM (non-streaming or accumulated). */
export interface ToolCall {
  id: string;
  type: "function";
  function: {
    name: string;
    arguments: string; // JSON string
  };
}

/** An incremental tool call delta from a streaming response. */
export interface ToolCallDelta {
  index: number;
  id?: string;
  type?: "function";
  function?: {
    name?: string;
    arguments?: string; // JSON fragment, accumulated across chunks
  };
}

export type ToolChoice =
  | "auto"
  | "none"
  | "required"
  | { type: "function"; function: { name: string } };

// ── Core Types ────────────────────────────────────────────────────────

export interface ChatMessage {
  role: ChatRole;
  content: string;
  name?: string;
  /** Tool calls generated by the assistant (native function calling). */
  tool_calls?: ToolCall[];
  /** ID of the tool call this message responds to (role: "tool"). */
  tool_call_id?: string;
}

export interface ChatCompletionRequest {
  messages: ChatMessage[];
  temperature?: number;
  maxTokens?: number;
  signal?: AbortSignal;
  /** The agent run this request belongs to (§P1-5). */
  runId?: string;
  /** Caller-provided model call ID. When set, ModelRouter uses this instead of generating one (§P1-5). */
  modelCallId?: string;
  /** Caller metadata to persist with the model call record (§P1-5). */
  metadata?: Record<string, unknown>;
  /** Tool definitions for native function calling. When set, the LLM may return tool_calls. */
  tools?: ToolDefinition[];
  /** Controls how the LLM uses tools. "auto" lets the LLM decide, "none" disables, "required" forces a tool call. */
  tool_choice?: ToolChoice;
  /** User-selected model ID — overrides purpose-based routing. */
  modelId?: "dp" | "seed";
}

/** User-selectable chat model identifier. */
export type ChatModelId = "dp" | "seed";

export interface ChatCompletionDelta {
  /** Text content delta. Empty string when the chunk contains only tool calls. */
  delta: string;
  /** Tool call deltas from a streaming function-calling response. Undefined for text-only chunks. */
  toolCalls?: ToolCallDelta[];
  raw: unknown;
}

export interface LlmProvider {
  id: string;
  model: string;
  streamChat(request: ChatCompletionRequest): AsyncIterable<ChatCompletionDelta>;
}

export interface OpenAICompatibleChatProviderConfig {
  /** Stable identifier for distinguishing providers in model_calls / traces. */
  id?: string;
  apiKey: string;
  baseUrl?: string;
  model?: string;
}

export type FetchLike = (input: string | URL, init?: RequestInit) => Promise<Response>;
